apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Basti\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml -o k8s/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: gatekeeper
  name: gatekeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gatekeeper
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Basti\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml -o k8s/
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: gatekeeper
    spec:
      containers:
        - env:
            - name: REDIS_URL
              value: redis://redis:6379
          image: gatekeeper_infonuagique:latest
          name: gatekeeper
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /certs
              name: certs
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: certs
          persistentVolumeClaim:
            claimName: certs
            readOnly: true
