apiVersion: v1
kind: Service
metadata:
  name: gatekeeper-quic
  namespace: extraction-mmo
spec:
  type: ClusterIP
  selector:
    app: gatekeeper
  ports:
    - name: quic
      port: 3001
      targetPort: 3001
      protocol: UDP
